server.port=${SERVER_PORT:8081}
spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}

consumer.topic=${TOPIC:psc-search}
consumer.group_id=${GROUP_ID:psc-search-consumer}
consumer.max_attempts=${MAX_ATTEMPTS:5}
consumer.backoff_delay=${BACKOFF_DELAY:1000}
consumer.concurrency=${CONCURRENT_LISTENER_INSTANCES:1}

invalid_message_topic=${INVALID_MESSAGE_TOPIC:invalid-messages}

logger.namespace=psc-search-consumer

management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/psc-search-consumer
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
debug=true

api.api-url=${API_URL:localhost}
api.api-key=${CHS_API_KEY:chsApiKey}